# 26 february numpy asssignments


Consider the below code to answer further questions:


import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]


array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.







In [2]:
import numpy as np


list_ = ['1','2','3','4','5']

array_list = np.array(list_)

In [3]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

ans  

list_ is a list while array_list is an array . both have different data type.

In [10]:
print('the list_has datatype  : ',type(list_))
print('the array_list has datatype  : ',type(array_list))

the list_has datatype  :  <class 'list'>
the array_list has datatype  :  <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.







In [14]:
# ans
# list(i for i in list_)

for i in list_ : 
    print(i,type(i))


1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [15]:
for i in array_list : 
    print(i,type(i))

1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)


Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.


ans 

Yes, there is a difference  in list_ it is showing only class str but in array_list , it is showing class numpy and str. 
it means that list_ is a list while array_list is an array.both have same data type str (string).





In [18]:
for i in list_:
    print(type(list_))


for i in array_list :
    print(type(array_list))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Consider the below code to answer further questions:


import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [26]:
import numpy as np

num_list = [[1,2,3],[4,5,6]]

num_array = np.array(num_list)
print(num_list)
print(num_array)
print('The size of the num_array is :',num_array.size)
print('The shape of the num_array is :',num_array.shape)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
The size of the num_array is : 6
The shape of the num_array is : (2, 3)



Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.


[Hint: The size of the array will be 9 and the shape will be (3,3).]



In [29]:
import numpy as np
arr = np.zeros((3,3))
print(arr)
print(arr.size)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
(3, 3)


Q6. Create an identity matrix of shape (5,5) using numpy functions?



[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
import numpy as np
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])